# Generated by Django 5.2 on 2026-08-12

import django.db.models
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    django.db.models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    django.db.models.EmailField(max_length=254, unique=True),
                ),
                ("full_name", django.db.models.CharField(max_length=255)),
            ],
            options={
                "db_table": "identity_user",
            },
        ),
    ]
