# Generated by Django 5.2 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialModel",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="credential",
                        serialize=False,
                        to="identity.usermodel",
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "identity_credential",
            },
        ),
    ]
